services:
  # Наш FastAPI бэкенд + веб-інтерфейс
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smart_travel_web
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      # Монтуємо код для Hot Reload під час розробки
      - .:/app
      # Ізолюємо локальне віртуальне середовище .venv від Linux-контейнера
      - /app/.venv
    restart: unless-stopped
